"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.updateLastElementBounds = exports.createChildContext = exports.createRenderContext = exports.renderElement = exports.render = void 0;
var renderer_1 = require("./renderer");
Object.defineProperty(exports, "render", { enumerable: true, get: function () { return renderer_1.render; } });
var renderer_2 = require("./renderer");
Object.defineProperty(exports, "renderElement", { enumerable: true, get: function () { return renderer_2.renderElement; } });
var context_1 = require("./context");
Object.defineProperty(exports, "createRenderContext", { enumerable: true, get: function () { return context_1.createRenderContext; } });
Object.defineProperty(exports, "createChildContext", { enumerable: true, get: function () { return context_1.createChildContext; } });
Object.defineProperty(exports, "updateLastElementBounds", { enumerable: true, get: function () { return context_1.updateLastElementBounds; } });
