export interface PropertyMeta {
  codeAttr: string;
  friendlyName: string;
  syntax: string;
  description: string;
  supportedTypes: string[];
}

export const PROPERTY_META: Record<string, PropertyMeta> = {
  x: {
    codeAttr: 'x',
    friendlyName: 'X',
    syntax: 'x=100',
    description: '元素水平位置坐标',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'line', 'table'],
  },
  y: {
    codeAttr: 'y',
    friendlyName: 'Y',
    syntax: 'y=200',
    description: '元素垂直位置坐标',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'line', 'table'],
  },
  w: {
    codeAttr: 'w',
    friendlyName: 'W',
    syntax: 'w=300',
    description: '元素宽度',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'table'],
  },
  h: {
    codeAttr: 'h',
    friendlyName: 'H',
    syntax: 'h=200',
    description: '元素高度',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'table'],
  },
  bg: {
    codeAttr: 'bg',
    friendlyName: 'Fill',
    syntax: 'bg=#ffffff',
    description: '背景填充颜色',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'table'],
  },
  b: {
    codeAttr: 'b',
    friendlyName: 'Border',
    syntax: 'b=#333333',
    description: '边框颜色',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'table'],
  },
  s: {
    codeAttr: 's',
    friendlyName: 'Width',
    syntax: 's=2',
    description: '边框/线条宽度',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'line'],
  },
  c: {
    codeAttr: 'c',
    friendlyName: 'Color',
    syntax: 'c=#000000',
    description: '文字或线条颜色',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'line'],
  },
  size: {
    codeAttr: 'size',
    friendlyName: 'Size',
    syntax: 'size=14',
    description: '字体大小',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'text-size': {
    codeAttr: 'text-size',
    friendlyName: 'Size',
    syntax: 'text-size=14',
    description: '字体大小（size 的别名）',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  r: {
    codeAttr: 'r',
    friendlyName: 'R',
    syntax: 'r=8',
    description: '矩形圆角半径',
    supportedTypes: ['rectangle'],
  },
  opacity: {
    codeAttr: 'opacity',
    friendlyName: 'Opacity',
    syntax: 'opacity=0.8',
    description: '透明度（0-1）',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  padding: {
    codeAttr: 'padding',
    friendlyName: 'Padding',
    syntax: 'padding=8',
    description: '内边距（所有方向）',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-top': {
    codeAttr: 'padding-top',
    friendlyName: 'P-T',
    syntax: 'padding-top=4',
    description: '上内边距',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-right': {
    codeAttr: 'padding-right',
    friendlyName: 'P-R',
    syntax: 'padding-right=4',
    description: '右内边距',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-bottom': {
    codeAttr: 'padding-bottom',
    friendlyName: 'P-B',
    syntax: 'padding-bottom=4',
    description: '下内边距',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-left': {
    codeAttr: 'padding-left',
    friendlyName: 'P-L',
    syntax: 'padding-left=4',
    description: '左内边距',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  align: {
    codeAttr: 'align',
    friendlyName: 'Align',
    syntax: 'align=l | c | r',
    description: '水平对齐方式：l=左, c=居中, r=右',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'vertical-align': {
    codeAttr: 'vertical-align',
    friendlyName: 'V-Align',
    syntax: 'vertical-align=t | m | b',
    description: '垂直对齐方式：t=上, m=中, b=下',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  bold: {
    codeAttr: 'bold',
    friendlyName: 'Bold',
    syntax: 'bold',
    description: '文字加粗',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  italic: {
    codeAttr: 'italic',
    friendlyName: 'Italic',
    syntax: 'italic',
    description: '文字斜体',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'text-decoration': {
    codeAttr: 'text-decoration',
    friendlyName: 'Decoration',
    syntax: 'text-decoration=underline',
    description: '文字装饰线',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'line-height': {
    codeAttr: 'line-height',
    friendlyName: 'Line Height',
    syntax: 'line-height=22',
    description: '文本行高',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'letter-spacing': {
    codeAttr: 'letter-spacing',
    friendlyName: 'Letter Spacing',
    syntax: 'letter-spacing=1',
    description: '字符间距',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'shadow-enabled': {
    codeAttr: 'shadow-enabled',
    friendlyName: 'Shadow',
    syntax: 'shadow-enabled',
    description: '启用阴影效果',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-x': {
    codeAttr: 'shadow-x',
    friendlyName: 'X',
    syntax: 'shadow-x=2',
    description: '阴影水平偏移',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-y': {
    codeAttr: 'shadow-y',
    friendlyName: 'Y',
    syntax: 'shadow-y=2',
    description: '阴影垂直偏移',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-blur': {
    codeAttr: 'shadow-blur',
    friendlyName: 'Blur',
    syntax: 'shadow-blur=4',
    description: '阴影模糊半径',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-color': {
    codeAttr: 'shadow-color',
    friendlyName: 'Color',
    syntax: 'shadow-color=#000000',
    description: '阴影颜色',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  style: {
    codeAttr: 'style',
    friendlyName: 'Style',
    syntax: 'style=solid | dashed | dotted',
    description: '线条样式（仅 Line 元素）',
    supportedTypes: ['line'],
  },
  label: {
    codeAttr: 'label',
    friendlyName: 'Label',
    syntax: 'label="text"',
    description: '线条标签文字',
    supportedTypes: ['line'],
  },
  'text-color': {
    codeAttr: 'text-color',
    friendlyName: 'Label Color',
    syntax: 'text-color=#ff0000',
    description: '线条标签文字颜色',
    supportedTypes: ['line'],
  },
  url: {
    codeAttr: 'url',
    friendlyName: 'URL',
    syntax: 'url=image.png',
    description: '图片资源路径',
    supportedTypes: ['image'],
  },
  border: {
    codeAttr: 'border',
    friendlyName: 'Border',
    syntax: 'border=1',
    description: '表格边框宽度',
    supportedTypes: ['table'],
  },
  cellspacing: {
    codeAttr: 'cellspacing',
    friendlyName: 'Spacing',
    syntax: 'cellspacing=2',
    description: '单元格间距',
    supportedTypes: ['table'],
  },
  colspan: {
    codeAttr: 'colspan',
    friendlyName: 'Colspan',
    syntax: 'colspan=2',
    description: '列合并数',
    supportedTypes: ['table-cell'],
  },
  rowspan: {
    codeAttr: 'rowspan',
    friendlyName: 'Rowspan',
    syntax: 'rowspan=2',
    description: '行合并数',
    supportedTypes: ['table-cell'],
  },
};
