export interface PropertyMeta {
  codeAttr: string;
  friendlyName: string;
  zhName: string;
  syntax: string;
  description: string;
  zhDescription: string;
  supportedTypes: string[];
}

export const PROPERTY_META: Record<string, PropertyMeta> = {
  x: {
    codeAttr: 'x',
    friendlyName: 'X',
    zhName: '水平位置',
    syntax: 'x=100',
    description: '元素水平位置坐标',
    zhDescription: '元素在画布上的水平位置坐标。通过拖拽元素或直接输入数值来调整，单位为像素。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'line', 'table'],
  },
  y: {
    codeAttr: 'y',
    friendlyName: 'Y',
    zhName: '垂直位置',
    syntax: 'y=200',
    description: '元素垂直位置坐标',
    zhDescription: '元素在画布上的垂直位置坐标。通过拖拽元素或直接输入数值来调整，单位为像素。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'line', 'table'],
  },
  w: {
    codeAttr: 'w',
    friendlyName: 'W',
    zhName: '宽度',
    syntax: 'w=300',
    description: '元素宽度',
    zhDescription: '元素的宽度，以像素为单位。控制元素在水平方向上的大小，可通过拖拽调整或在代码中直接设置。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'table'],
  },
  h: {
    codeAttr: 'h',
    friendlyName: 'H',
    zhName: '高度',
    syntax: 'h=200',
    description: '元素高度',
    zhDescription: '元素的高度，以像素为单位。控制元素在垂直方向上的大小，可通过拖拽调整或在代码中直接设置。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'image', 'table'],
  },
  bg: {
    codeAttr: 'bg',
    friendlyName: 'Fill',
    zhName: '填充色',
    syntax: 'bg=#ffffff',
    description: '背景填充颜色',
    zhDescription: '元素的背景填充颜色。支持十六进制颜色值（如 #ffffff 表示白色）和 transparent（透明）。点击色块可打开颜色选择器。',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'table'],
  },
  b: {
    codeAttr: 'b',
    friendlyName: 'Border',
    zhName: '边框色',
    syntax: 'b=#333333',
    description: '边框颜色或线段颜色',
    zhDescription: '元素的边框颜色或线段的颜色。支持十六进制颜色值（如 #333333 表示深灰色）。点击色块可打开颜色选择器。',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'table', 'line'],
  },
  s: {
    codeAttr: 's',
    friendlyName: 'Width',
    zhName: '边框宽度',
    syntax: 's=2',
    description: '边框/线条宽度',
    zhDescription: '边框或线条的宽度，以像素为单位。数值越大边框越粗，设为 0 则不显示边框。可拖拽标签快速调整数值。',
    supportedTypes: ['rectangle', 'circle', 'placeholder', 'image', 'line'],
  },
  c: {
    codeAttr: 'c',
    friendlyName: 'Color',
    zhName: '文字色',
    syntax: 'c=#000000',
    description: '文字颜色',
    zhDescription: '文字的颜色。支持十六进制颜色值（如 #000000 表示黑色）。点击色块可打开颜色选择器。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder', 'line'],
  },
  size: {
    codeAttr: 'size',
    friendlyName: 'Size',
    zhName: '字号',
    syntax: 'size=14',
    description: '字体大小',
    zhDescription: '字体大小，以像素为单位。控制文字的显示大小，可拖拽标签快速调整数值。常用值：12（小）、14（标准）、18（大）、24（标题）。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'text-size': {
    codeAttr: 'text-size',
    friendlyName: 'Size',
    zhName: '字号',
    syntax: 'text-size=14',
    description: '字体大小（size 的别名）',
    zhDescription: '字体大小的另一种写法，与 size 属性功能相同。以像素为单位，控制文字的显示大小。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  r: {
    codeAttr: 'r',
    friendlyName: 'R',
    zhName: '圆角',
    syntax: 'r=8',
    description: '矩形圆角半径',
    zhDescription: '矩形的圆角半径，以像素为单位。0 为直角，值越大圆角越明显。当值足够大时，矩形会变为胶囊形或圆形。',
    supportedTypes: ['rectangle'],
  },
  opacity: {
    codeAttr: 'opacity',
    friendlyName: 'Opacity',
    zhName: '透明度',
    syntax: 'opacity=0.8',
    description: '透明度（0-1）',
    zhDescription: '元素的透明度，取值范围 0 到 1。0 为完全透明（不可见），1 为完全不透明。可通过滑块或输入框调整。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  padding: {
    codeAttr: 'padding',
    friendlyName: 'Padding',
    zhName: '内边距',
    syntax: 'padding=8',
    description: '内边距（所有方向）',
    zhDescription: '元素的内边距，即内容与边框之间的距离。设置后四个方向统一使用相同的值。也可单独设置各方向的内边距。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-top': {
    codeAttr: 'padding-top',
    friendlyName: 'P-T',
    zhName: '上边距',
    syntax: 'padding-top=4',
    description: '上内边距',
    zhDescription: '上方的内边距，即内容与上边框之间的距离，以像素为单位。单独设置可覆盖 padding 的统一值。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-right': {
    codeAttr: 'padding-right',
    friendlyName: 'P-R',
    zhName: '右边距',
    syntax: 'padding-right=4',
    description: '右内边距',
    zhDescription: '右侧的内边距，即内容与右边框之间的距离，以像素为单位。单独设置可覆盖 padding 的统一值。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-bottom': {
    codeAttr: 'padding-bottom',
    friendlyName: 'P-B',
    zhName: '下边距',
    syntax: 'padding-bottom=4',
    description: '下内边距',
    zhDescription: '下方的内边距，即内容与下边框之间的距离，以像素为单位。单独设置可覆盖 padding 的统一值。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  'padding-left': {
    codeAttr: 'padding-left',
    friendlyName: 'P-L',
    zhName: '左边距',
    syntax: 'padding-left=4',
    description: '左内边距',
    zhDescription: '左侧的内边距，即内容与左边框之间的距离，以像素为单位。单独设置可覆盖 padding 的统一值。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  align: {
    codeAttr: 'align',
    friendlyName: 'Align',
    zhName: '水平对齐',
    syntax: 'align=l | c | r',
    description: '水平对齐方式：l=左, c=居中, r=右',
    zhDescription: '文字的水平对齐方式。l（left）= 左对齐，c（center）= 居中对齐，r（right）= 右对齐。默认为左对齐。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'vertical-align': {
    codeAttr: 'vertical-align',
    friendlyName: 'V-Align',
    zhName: '垂直对齐',
    syntax: 'vertical-align=t | m | b',
    description: '垂直对齐方式：t=上, m=中, b=下',
    zhDescription: '文字的垂直对齐方式。t（top）= 顶部对齐，m（middle）= 垂直居中，b（bottom）= 底部对齐。默认为顶部对齐。',
    supportedTypes: ['rectangle', 'circle', 'placeholder'],
  },
  bold: {
    codeAttr: 'bold',
    friendlyName: 'Bold',
    zhName: '粗体',
    syntax: 'bold',
    description: '文字加粗',
    zhDescription: '文字加粗开关。启用后文字以粗体显示，使文字更加醒目。再次点击可取消加粗。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  italic: {
    codeAttr: 'italic',
    friendlyName: 'Italic',
    zhName: '斜体',
    syntax: 'italic',
    description: '文字斜体',
    zhDescription: '文字斜体开关。启用后文字以斜体显示，常用于强调或引用。再次点击可取消斜体。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'text-decoration': {
    codeAttr: 'text-decoration',
    friendlyName: 'Decoration',
    zhName: '文字装饰',
    syntax: 'text-decoration=underline',
    description: '文字装饰线',
    zhDescription: '文字装饰线类型。underline = 下划线（文字下方添加线条），line-through = 删除线（文字中间添加线条）。两种装饰不可同时使用。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'line-height': {
    codeAttr: 'line-height',
    friendlyName: 'Line Height',
    zhName: '行高',
    syntax: 'line-height=22',
    description: '文本行高',
    zhDescription: '文本行高，以像素为单位。控制多行文字之间的行间距，值越大行间距越大。建议设为字号的 1.4~1.8 倍以获得良好的阅读体验。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'letter-spacing': {
    codeAttr: 'letter-spacing',
    friendlyName: 'Letter Spacing',
    zhName: '字间距',
    syntax: 'letter-spacing=1',
    description: '字符间距',
    zhDescription: '字符间距，以像素为单位。正值增大字符之间的间距，负值缩小间距。默认为 0，常用于标题文字的排版调整。',
    supportedTypes: ['rectangle', 'circle', 'text', 'placeholder'],
  },
  'shadow-enabled': {
    codeAttr: 'shadow-enabled',
    friendlyName: 'Shadow',
    zhName: '阴影',
    syntax: 'shadow-enabled',
    description: '启用阴影效果',
    zhDescription: '阴影效果开关。勾选后可为元素添加投影效果，使元素具有立体感。启用后需配合阴影偏移、模糊和颜色属性使用。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-x': {
    codeAttr: 'shadow-x',
    friendlyName: 'X',
    zhName: '阴影X',
    syntax: 'shadow-x=2',
    description: '阴影水平偏移',
    zhDescription: '阴影的水平偏移量，以像素为单位。正值向右偏移，负值向左偏移。默认为 0，表示阴影与元素水平对齐。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-y': {
    codeAttr: 'shadow-y',
    friendlyName: 'Y',
    zhName: '阴影Y',
    syntax: 'shadow-y=2',
    description: '阴影垂直偏移',
    zhDescription: '阴影的垂直偏移量，以像素为单位。正值向下偏移，负值向上偏移。默认为 0，表示阴影与元素垂直对齐。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-blur': {
    codeAttr: 'shadow-blur',
    friendlyName: 'Blur',
    zhName: '阴影模糊',
    syntax: 'shadow-blur=4',
    description: '阴影模糊半径',
    zhDescription: '阴影的模糊半径，以像素为单位。值越大阴影越模糊扩散，值越小阴影越锐利。默认为 3，设为 0 则阴影边缘完全清晰。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  'shadow-color': {
    codeAttr: 'shadow-color',
    friendlyName: 'Color',
    zhName: '阴影色',
    syntax: 'shadow-color=#000000',
    description: '阴影颜色',
    zhDescription: '阴影的颜色。支持十六进制颜色值（如 #000000 表示黑色）。通常使用深色配合较低的透明度来模拟自然阴影效果。',
    supportedTypes: ['rectangle', 'circle', 'text', 'image'],
  },
  style: {
    codeAttr: 'style',
    friendlyName: 'Style',
    zhName: '线条样式',
    syntax: 'style=solid | dashed | dotted',
    description: '线条样式（仅 Line 元素）',
    zhDescription: '线条的绘制样式，仅适用于线段元素。solid = 实线（默认），dashed = 虚线，dotted = 点线。',
    supportedTypes: ['line'],
  },
  label: {
    codeAttr: 'label',
    friendlyName: 'Content',
    zhName: '内容',
    syntax: '-"text"-',
    description: '线段文字内容',
    zhDescription: '线段上的文字内容，显示在线段的中间位置。常用于标注线段的含义或方向。',
    supportedTypes: ['line'],
  },
  url: {
    codeAttr: 'url',
    friendlyName: 'URL',
    zhName: '图片路径',
    syntax: 'url=image.png',
    description: '图片资源路径',
    zhDescription: '图片资源的文件路径。支持相对路径和绝对路径，常见格式包括 jpg、png、gif、svg。可点击右侧按钮浏览选择文件。',
    supportedTypes: ['image'],
  },
  border: {
    codeAttr: 'border',
    friendlyName: 'Border',
    zhName: '边框宽度',
    syntax: 'border=1',
    description: '表格边框宽度',
    zhDescription: '表格的边框宽度，以像素为单位。控制表格整体边框线的粗细，影响所有单元格的边框显示。',
    supportedTypes: ['table'],
  },
  cellspacing: {
    codeAttr: 'cellspacing',
    friendlyName: 'Spacing',
    zhName: '单元格间距',
    syntax: 'cellspacing=2',
    description: '单元格间距',
    zhDescription: '表格单元格之间的间距，以像素为单位。值越大单元格之间的空隙越明显，设为 0 则单元格紧密排列。',
    supportedTypes: ['table'],
  },
  colspan: {
    codeAttr: 'colspan',
    friendlyName: 'Colspan',
    zhName: '列合并',
    syntax: 'colspan=2',
    description: '列合并数',
    zhDescription: '单元格横向合并的列数。用于创建跨列的合并单元格，值为 2 表示合并当前列和右侧一列。',
    supportedTypes: ['table-cell'],
  },
  rowspan: {
    codeAttr: 'rowspan',
    friendlyName: 'Rowspan',
    zhName: '行合并',
    syntax: 'rowspan=2',
    description: '行合并数',
    zhDescription: '单元格纵向合并的行数。用于创建跨行的合并单元格，值为 2 表示合并当前行和下方一行。',
    supportedTypes: ['table-cell'],
  },
  x2: {
    codeAttr: 'x2',
    friendlyName: 'X2',
    zhName: '终点X',
    syntax: 'x2=200',
    description: '线段终点水平坐标',
    zhDescription: '线段终点的水平位置坐标，以像素为单位。与起点坐标共同确定线段的位置和方向。',
    supportedTypes: ['line'],
  },
  y2: {
    codeAttr: 'y2',
    friendlyName: 'Y2',
    zhName: '终点Y',
    syntax: 'y2=300',
    description: '线段终点垂直坐标',
    zhDescription: '线段终点的垂直位置坐标，以像素为单位。与起点坐标共同确定线段的位置和方向。',
    supportedTypes: ['line'],
  },
  pt: {
    codeAttr: 'pt',
    friendlyName: 'P-T',
    zhName: '上边距',
    syntax: 'pt=4',
    description: '单元格上内边距',
    zhDescription: '表格单元格上方的内边距，即文字与单元格上边框之间的距离，以像素为单位。',
    supportedTypes: ['table-cell'],
  },
  pr: {
    codeAttr: 'pr',
    friendlyName: 'P-R',
    zhName: '右边距',
    syntax: 'pr=4',
    description: '单元格右内边距',
    zhDescription: '表格单元格右侧的内边距，即文字与单元格右边框之间的距离，以像素为单位。',
    supportedTypes: ['table-cell'],
  },
  pb: {
    codeAttr: 'pb',
    friendlyName: 'P-B',
    zhName: '下边距',
    syntax: 'pb=4',
    description: '单元格下内边距',
    zhDescription: '表格单元格下方的内边距，即文字与单元格下边框之间的距离，以像素为单位。',
    supportedTypes: ['table-cell'],
  },
  pl: {
    codeAttr: 'pl',
    friendlyName: 'P-L',
    zhName: '左边距',
    syntax: 'pl=4',
    description: '单元格左内边距',
    zhDescription: '表格单元格左侧的内边距，即文字与单元格左边框之间的距离，以像素为单位。',
    supportedTypes: ['table-cell'],
  },
};
