import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import fs from "fs";
import path from "path";
import { logger } from "../middleware/logger.js";

interface ProjectStructure {
  frontendFiles: string[];
  backendFiles: string[];
  configFiles: string[];
  techStack: string[];
}

function scanProject(basePath: string, frontendPaths: string[], backendPaths: string[]): ProjectStructure {
  const result: ProjectStructure = {
    frontendFiles: [],
    backendFiles: [],
    configFiles: [],
    techStack: [],
  };

  const scanDir = (dirPath: string, patterns: string[], target: "frontend" | "backend" | "config") => {
    if (!fs.existsSync(dirPath)) return;

    const walk = (currentPath: string) => {
      const entries = fs.readdirSync(currentPath, { withFileTypes: true });
      for (const entry of entries) {
        const fullPath = path.join(currentPath, entry.name);
        if (entry.name === "node_modules" || entry.name === ".git") continue;

        if (entry.isDirectory()) {
          walk(fullPath);
        } else {
          const relativePath = path.relative(basePath, fullPath);
          if (target === "frontend" && patterns.some((p) => relativePath.includes(p))) {
            result.frontendFiles.push(relativePath);
          } else if (target === "backend" && patterns.some((p) => relativePath.includes(p))) {
            result.backendFiles.push(relativePath);
          } else if (target === "config") {
            result.configFiles.push(relativePath);
          }
        }
      }
    };

    walk(dirPath);
  };

  scanDir(path.join(basePath, frontendPaths[0] || "src"), [".tsx", ".jsx", ".vue", ".html"], "frontend");
  scanDir(path.join(basePath, backendPaths[0] || "api"), [".ts", ".js", ".py", ".go"], "backend");

  // Detect tech stack
  const pkgPath = path.join(basePath, "package.json");
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    const deps = { ...pkg.dependencies, ...pkg.devDependencies };
    if (deps.react || deps["@types/react"]) result.techStack.push("React");
    if (deps.vue) result.techStack.push("Vue");
    if (deps.express) result.techStack.push("Express");
    if (deps.nestjs || deps["@nestjs/core"]) result.techStack.push("NestJS");
    if (deps.next) result.techStack.push("Next.js");
    if (deps["tailwindcss"]) result.techStack.push("Tailwind CSS");
  }

  return result;
}

function extractUserStories(structure: ProjectStructure): string {
  const stories = [];
  if (structure.frontendFiles.length > 0) {
    stories.push("US-001 | As a user, I want to interact with the UI | Given context, when action, then result | P0");
  }
  if (structure.backendFiles.length > 0) {
    stories.push("US-002 | As a system, I need to process API requests | Given request, when processed, then response | P0");
  }
  return stories.map((s) => `| ${s} |`).join("\n");
}

function generatePrdContent(projectName: string, structure: ProjectStructure): string {
  const userStories = extractUserStories(structure);

  return `# Product Requirements Document - ${projectName}

## Document Information
| Item | Details |
|------|---------|
| Project Name | ${projectName} |
| Version | v1.0 |
| Created Date | ${new Date().toISOString().split("T")[0]} |
| Author | Generated by code-to-prd analysis |
| Tech Stack | ${structure.techStack.join(", ") || "To be confirmed"} |

---

## 1. Product Overview

### 1.1 Product Background
This PRD was reverse-engineered from the existing codebase at ${new Date().toISOString().split("T")[0]}.

### 1.2 Target Users
[To be confirmed based on code analysis]

### 1.3 Core Value
[To be confirmed - inferred from main features]

### 1.4 User Stories

| ID | User Story | Acceptance Criteria | Priority |
|----|------------|---------------------|----------|
${userStories}

---

## 2. Feature Scope

### 2.1 Feature List
| Module | Feature | Priority | Description |
|--------|---------|----------|-------------|
| Frontend | UI Components | P0 | ${structure.frontendFiles.length} files detected |
| Backend | API Endpoints | P0 | ${structure.backendFiles.length} files detected |

### 2.2 Feature Boundary
- Included: Features detected in codebase
- Not Included: [To be confirmed]

---

## 3. Business Flow

### 3.1 Core Business Flowchart
\`\`\`mermaid
flowchart TD
    A[Start] --> B[User Action]
    B --> C[Frontend Processing]
    C --> D[API Request]
    D --> E[Backend Processing]
    E --> F[Response]
    F --> G[Update UI]
\`\`\`

---

## 4. Page Design

### 4.1 Page List
| Page Name | Page Type | Description |
|-----------|-----------|-------------|
| [To be confirmed] | [To be confirmed] | [To be confirmed] |

---

## 5. Page Details

[To be confirmed - AI should analyze frontend files and generate SolarWire wireframes]

---

## 6. Non-functional Requirements

### 6.1 Performance Requirements
- Page load time: < 2 seconds
- API response time: < 500ms

### 6.2 Security Requirements
- [To be confirmed based on auth middleware]

---

## 7. Appendix

### 7.1 API Reference
[To be confirmed - analyze backend routes]

### 7.2 Data Models
[To be confirmed - analyze database schemas]
`;
}

export function registerCodeToPrdTool(server: McpServer) {
  server.tool(
    "code-to-prd",
    "Reverse engineer frontend/backend code into complete PRD documents with SolarWire wireframes. Scans codebase structure, extracts UI components, API endpoints, and generates documentation.",
    {
      codebasePath: z.string().describe("Path to the codebase directory"),
      frontendPath: z.string().optional().default("src").describe("Frontend source directory"),
      backendPath: z.string().optional().default("api").describe("Backend source directory"),
      projectName: z.string().describe("Project name for output directory"),
      outputDir: z.string().optional().default("./output").describe("Output directory (default: .solarwire)"),
    },
    async ({ codebasePath, frontendPath, backendPath, projectName, outputDir }) => {
      try {
        logger.info(`Starting code-to-prd analysis for: ${projectName}`);

        const basePath = path.resolve(codebasePath);
        if (!fs.existsSync(basePath)) {
          return {
            content: [{ type: "text", text: `Error: Codebase path not found: ${basePath}` }],
            isError: true,
          };
        }

        // Scan project structure
        const structure = scanProject(basePath, [frontendPath], [backendPath]);

        logger.info(`Scan complete: ${structure.frontendFiles.length} frontend, ${structure.backendFiles.length} backend files`);

        // Generate PRD content
        const prdContent = generatePrdContent(projectName, structure);

        // Save PRD file
        const outDir = path.resolve(outputDir);
        if (!fs.existsSync(outDir)) {
          fs.mkdirSync(outDir, { recursive: true });
        }

        const prdFile = path.join(outDir, `${projectName.toLowerCase().replace(/\s+/g, "-")}-prd.md`);
        fs.writeFileSync(prdFile, prdContent, "utf-8");
        logger.info(`PRD saved to: ${prdFile}`);

        const result = {
          success: true,
          message: "Code-to-PRD analysis completed",
          output: {
            file: prdFile,
            projectName,
            techStack: structure.techStack,
            frontendFileCount: structure.frontendFiles.length,
            backendFileCount: structure.backendFiles.length,
            configFiles: structure.configFiles,
          },
          nextSteps: [
            "Review the generated PRD",
            "AI should analyze frontend files to generate SolarWire wireframes",
            "AI should analyze backend routes to document API endpoints",
            "Update [To be confirmed] sections with actual data",
          ],
        };

        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        logger.error(`Code-to-PRD failed: ${errorMessage}`);
        return {
          content: [
            {
              type: "text",
              text: `Error: ${errorMessage}`,
            },
          ],
          isError: true,
        };
      }
    }
  );
}
