import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { logger } from "../middleware/logger.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CONTAINER_SIZES: Record<string, { w: number; h: number }> = {
  mobile: { w: 375, h: 812 },
  web: { w: 1440, h: 900 },
  dashboard: { w: 1920, h: 1080 },
  other: { w: 1440, h: 900 },
};

function generateUserStories(features: string[]): string {
  const stories = features.map((f, i) => {
    const id = `US-${String(i + 1).padStart(3, "0")}`;
    return `| ${id} | As a user, I want to ${f.trim()} | Given context, when action, then result | P${i === 0 ? "0" : "1"} |`;
  });
  return stories.join("\n");
}

function generateSolarWireExample(projectName: string, productType: string, features: string[]): string {
  const size = CONTAINER_SIZES[productType] || CONTAINER_SIZES.web;
  const featureList = features.slice(0, 3).map((f, i) => `    ${f.trim().substring(0, 20)}`);

  return `!title="${projectName} - Main Page"
!c=#111827
!size=13
!bg=#F9FAFB
!r=0

// Container
[] @(0,0) w=${size.w} h=${size.h} bg=#FFFFFF

// Header
[] @(0,0) w=${size.w} h=60 bg=#F5F5F5
"${projectName}" @(20,15) size=20 bold

// Navigation
"Home" @(20,75) c=#3B82F6 bold
"Features" @(${size.w / 2 - 50},75)
"Settings" @(${size.w - 100},75)

// Main Content
"Welcome to ${projectName}" @(20,100) size=18 bold

${featureList.map((f, i) => `[] @(20,${130 + i * 50}) w=${size.w - 40} h=40 bg=#FFFFFF b=#E5E7EB r=8
"${f}" @(40,${140 + i * 50})`).join("\n")}

// Footer
-- @(0,${size.h - 40})->(${size.w},${size.h - 40}) b=#E5E7EB
"© 2024 ${projectName}" @(20,${size.h - 30}) c=#9CA3AF`;
}

function generateMermaidFlowchart(features: string[]): string {
  const steps = features.map((f, i) => {
    const label = f.trim().substring(0, 30);
    return `    B[${label}]`;
  }).join("\n");

  return `flowchart TD
    A[Start] --> ${features.length > 0 ? "B" : "C"}
${features.map((_, i) => {
    if (i === features.length - 1) return `    B${i > 0 ? i + 1 : ""}[Action ${i + 1}] --> C[End]`;
    return `    B${i > 0 ? i + 1 : ""}[Action ${i + 1}] --> B${i + 2}[Action ${i + 2}]`;
  }).join("\n")}`;
}

export function registerGeneratePrdTool(server: McpServer) {
  server.tool(
    "generate-prd",
    "Generate a complete PRD document with SolarWire wireframes, Mermaid diagrams, and save to file",
    {
      projectName: z.string().describe("Project name"),
      productType: z.enum(["mobile", "web", "dashboard", "other"]).describe("Product type"),
      features: z.string().describe("Core features list, comma separated"),
      targetUsers: z.string().optional().default("General users").describe("Target users description"),
      outputPath: z.string().optional().default("./output").describe("Output directory for PRD file"),
      multiLanguage: z.boolean().optional().default(false).describe("Whether multi-language support is needed"),
    },
    async ({ projectName, productType, features, targetUsers, outputPath, multiLanguage }) => {
      try {
        logger.info("Generating PRD", { projectName, productType });

        const featureList = features.split(",").map((f) => f.trim()).filter(Boolean);
        const outputDir = path.resolve(outputPath);
        const outputFileName = `${projectName.toLowerCase().replace(/\s+/g, "-")}-prd.md`;
        const outputFile = path.join(outputDir, outputFileName);

        // Ensure output directory exists
        if (!fs.existsSync(outputDir)) {
          fs.mkdirSync(outputDir, { recursive: true });
        }

        const containerSize = CONTAINER_SIZES[productType];
        const solarWireCode = generateSolarWireExample(projectName, productType, featureList);
        const mermaidFlowchart = generateMermaidFlowchart(featureList);
        const userStories = generateUserStories(featureList);

        const prdContent = `# Product Requirements Document - ${projectName}

## Document Information
| Item | Details |
|------|---------|
| Project Name | ${projectName} |
| Version | v1.0 |
| Created Date | ${new Date().toISOString().split("T")[0]} |
| Author | Generated by SolarWire MCP Server |
| Product Type | ${productType} |

---

## 1. Product Overview

### 1.1 Product Background
${projectName} is a ${productType} application designed for ${targetUsers}.

### 1.2 Target Users
${targetUsers}

### 1.3 Core Value
This product solves the following user needs:
${featureList.map((f) => `- ${f}`).join("\n")}

### 1.4 User Stories

| ID | User Story | Acceptance Criteria | Priority |
|----|------------|---------------------|----------|
${userStories}

---

## 2. Feature Scope

### 2.1 Feature List
| Module | Feature | Priority | Description |
|--------|---------|----------|-------------|
${featureList.map((f, i) => `| Core | ${f} | P${i === 0 ? "0" : "1"} | ${f} |`).join("\n")}

### 2.2 Feature Boundary
- Included: ${featureList.join(", ")}
- Not Included: Future versions

---

## 3. Business Flow

### 3.1 Core Business Flowchart
\`\`\`mermaid
${mermaidFlowchart}
\`\`\`

---

## 4. Page Design

### 4.1 Page List
| Page Name | Page Type | Description |
|-----------|-----------|-------------|
| Main Page | ${productType} | Main entry point |
| Settings Page | ${productType} | User settings |

---

## 5. Page Details

### 5.1 Main Page

\`\`\`solarwire
${solarWireCode}
\`\`\`

---

## 6. Non-functional Requirements

### 6.1 Performance Requirements
- Page load time: < 2 seconds
- API response time: < 500ms

### 6.2 Security Requirements
- User authentication required
- Data encryption in transit

### 6.3 Compatibility Requirements
- Browsers: Chrome 90+, Safari 14+, Firefox 88+
- Mobile: iOS 14+, Android 10+
${multiLanguage ? "- Multi-language support: English, Chinese, Japanese" : ""}

---

## 7. Appendix

### 7.1 SolarWire Syntax Reference
All wireframes use absolute coordinates @(x,y) and direct attributes (w=, h=, bg=, etc.).
`;

        // Write PRD file
        fs.writeFileSync(outputFile, prdContent, "utf-8");
        logger.info(`PRD written to: ${outputFile}`);

        const result = {
          success: true,
          message: "PRD generated and saved successfully",
          output: {
            file: outputFile,
            projectName,
            productType,
            featureCount: featureList.length,
            includesWireframe: true,
            includesMermaid: true,
            multiLanguage,
          },
        };

        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2),
            },
          ],
        };
      } catch (error) {
        logger.error("PRD generation failed", { error });
        return {
          content: [
            {
              type: "text",
              text: `Error: ${error instanceof Error ? error.message : String(error)}`,
            },
          ],
          isError: true,
        };
      }
    }
  );
}
